cat >> /etc/XrayR/config.yml <<EOF
Log:
  Level: warning
  AccessPath: 
  ErrorPath: 

DnsConfigPath: 
RouteConfigPath: 

OutboundConfig:
  Enable: false

Nodes:
  -
    PanelType: "NewV2board"
    ApiConfig:
      ApiHost: "" 
      ApiKey: ""
      NodeID: 2
      NodeType: Shadowsocks
      Timeout: 30
      EnableVless: false
      EnableXTLS: false
      SpeedLimit: 10  #每个用户限速10M

    ControllerConfig:
      ListenIP: 0.0.0.0
      SendIP: 0.0.0.0
      UpdatePeriodic: 60
      EnableDNS: false
      DNSType: AsIs
      EnableProxyProtocol: false
      EnableSniffing: false
      AutoSpeedLimitConfig:
        Limit: 50 #到达50M限速10M
        WarnTimes: 0
        LimitSpeed: 10 #限速10M
        LimitDuration: 5 #限速5分钟
EOF
